### ISSUE TITLE
method of limits (corrupted)

### ISSUE THREAD

**Issue by SantiGarciaG** [SantiGarciaG/AA_expII#7] opened 2017-11-16 12:59 UTC
Something was changed with the last changes we made. I have been testing the version and the way the points are supposed to increase or decrease doesn't make sense any more. In the current version, it seems that no matter what the person does chooing the threat option always decreases. 

The way it's supposed to work (as it was working well before) is:

* If the safe option is preferred, the threat option is increased. 
* If the threat option is preferred (e.g., after switch 1), the threat option is decreased (providing upper bound value). 
* If safe option is preferred, as a consequence of the reduction in threat (e.g., switch 2), the threat option would technically increase again [this is not happening, so way would anybody switch ever back again]. **But since this would be switch 2, the experiment would terminate here and thus providing us with the lower bound**. 

_For example: a fearful participant prefers "safe" (10 vs 12...), then at 10 vs 18 s/he prefers "threat" (avoid-approach; switch 1; upper bound = 18), then in the next bock when it is 10 vs 16, s/he goes back to preferring "safe" (approach-avoid; switch 2; lower bound = 16)._     

Case/ConditionII
* If a participant, on the other hand, prefers the threat option from the beginning, then this option is reduced for as long as this is the case. When s/he then switches to the safe option (presumably when the threat value is lower than 10), this would be switch 1 and the threat option would increase until the person switches back to threat (switch 2) thereby terminating the experiment. 

I think these two different conditions, got mixed in some point.

**Comment by cherepaha** [comment] 2017-11-16 13:30
Hi Santi, can you confirm this issue arises in the current version? I cannot reproduce it... See my recent comment to Issue #6, there was a problem with p_threat which could lead to threat reward always decreasing. However, this was supposed to be fixed with the update I pushed yesterday.

**Comment by SantiGarciaG** [comment] 2017-11-16 16:28
It is still there (_I have updated the issue slightly to better illustrate the desirable mechanics_). If you test it with 4 blocks, start avoiding and then, when you reach 10vs16 for example, switch to safe option... you'll notice that for as long as you keep on preferring the safe option the threat keep on decreasing (instead on increasing as it should be the case). **Now I have a feeling that this is because the switching count might've been affected too?** Remember that the increase/decrease, as well as the switch count, takes effect as a consequence of preferring one option over the other in the current block (even though the result of more/less points are only visible for the next block --I don't know if this makes sense). But I'm trying to say, is that it seems like we added an extra switch somewhere. Right now the lower bound is taken --I believe-- from the second preferred threat (assuming a fearful participant), so the switches go like: avoid-approach (No 1), approach-avoid (No 2), and avoid-approach again (No 3).

**Comment by cherepaha** [comment] 2017-11-17 04:58
Great, thanks for detailed example. I've been able to spot the issue, we just needed to check for p_threat>0.5 instead of p_threat<0 in the reversed sequence. Now it seems to work just fine for the example you described. However, I didn't have time to test it thoroughly by going up to the maximum number of blocks, do you mind checking this please?

**Closed as completed** 2017-11-17 15:26 UTC
